name: Project Build and Test

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  Build-Test:
    uses: Mhodtood/mhodtood-devops/.github/workflows/rust-build-test.yaml@main
