name: Security audit
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "**/Cargo.toml"
  #     - "**/Cargo.lock"
jobs:
  security_audit:
    uses: Mhodtood/mhodtood-devops/.github/workflows/rust-security-audit.yaml@main
